<?php require_once __DIR__.'/../core.php';
if(!is_admin()){ header('Location:/modules/connexion.php?redirect='.rawurlencode('/modules/city3d.php')); exit; }
require_role('lotissement');
$s=settings();
?>
<!doctype html><html lang="fr"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GEA-H Smart City Studio — Lotissement IA</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,system-ui,sans-serif;background:#07120f;color:#eef5f0;overflow:hidden}
.top{position:fixed;top:0;left:0;right:0;height:56px;background:linear-gradient(90deg,#042017,#0b3729);display:flex;align-items:center;gap:12px;padding:0 16px;z-index:50;border-bottom:1px solid rgba(212,162,58,.35)}
.top .brand{font-weight:900;color:#d4a23a;letter-spacing:.3px}.top a{color:#dbe7e0;text-decoration:none;font-size:14px}.badge{font-size:11px;background:#d4a23a;color:#241600;border-radius:999px;padding:4px 8px;font-weight:800}
.layout{position:fixed;top:56px;left:0;right:0;bottom:0;display:grid;grid-template-columns:340px 1fr 330px;min-width:980px}
.panel{background:#0b1d18;border-right:1px solid rgba(255,255,255,.08);overflow:auto;padding:14px}.right{border-left:1px solid rgba(255,255,255,.08);border-right:0}
.stage{position:relative;background:#0d171f}.canvas3d{width:100%;height:100%;display:block}.map2d{position:absolute;inset:0;display:none;background:#10231d}.map2d canvas{width:100%;height:100%;display:block}.map2d.active{display:block}.canvas3d.hidden{display:none}
h2{margin:0 0 10px;font-size:18px;color:#d4a23a}.sec{border:1px solid rgba(212,162,58,.16);background:rgba(255,255,255,.035);border-radius:14px;padding:12px;margin-bottom:12px}.sec h3{margin:0 0 8px;font-size:13px;color:#f6d78c;text-transform:uppercase;letter-spacing:.5px}
label{font-size:12px;color:#b9d8cb;display:block;margin:8px 0 4px}input,select,textarea{width:100%;border:1px solid #24493d;background:#07130f;color:#fff;border-radius:10px;padding:9px;font-size:13px}textarea{min-height:92px;resize:vertical}.row{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #2c5b4c;background:#10382d;color:#fff;border-radius:10px;padding:9px 10px;cursor:pointer;font-size:13px;flex:1 0 auto}.btn:hover{background:#164a3c}.btn.gold{background:#d4a23a;color:#211400;border:0;font-weight:900}.btn.red{background:#7f1d1d;border:0}.btn.blue{background:#155e75;border:0}.btn.dark{background:#0b1720}.small{font-size:12px;color:#a8c8bd;line-height:1.45}.cards{display:grid;grid-template-columns:1fr 1fr;gap:8px}.card{border:1px solid #24493d;background:#09211a;border-radius:12px;padding:10px;cursor:pointer;font-size:12px}.card:hover{border-color:#d4a23a}.card b{display:block;color:#fff;margin-bottom:4px}.stats{display:grid;grid-template-columns:1fr 1fr;gap:8px}.stat{background:#06120f;border:1px solid #1e3d33;border-radius:12px;padding:10px}.stat b{display:block;color:#d4a23a;font-size:18px}.mini{font-size:11px;color:#9fb}.hint{position:absolute;left:18px;bottom:14px;background:rgba(0,0,0,.62);border:1px solid rgba(212,162,58,.25);padding:9px 12px;border-radius:999px;font-size:12px;color:#e9fff6;z-index:3}.paywall{background:linear-gradient(135deg,rgba(212,162,58,.18),rgba(11,55,41,.38));border:1px solid rgba(212,162,58,.35)}
.ai{background:linear-gradient(135deg,#06120f,#0d2d23);border-color:#2b6b59}.aiReply{white-space:pre-wrap;background:#06120f;border:1px solid #22463a;border-radius:12px;padding:10px;font-size:12px;line-height:1.45;color:#dceee7}.legend span{display:inline-flex;align-items:center;gap:5px;margin:3px 8px 3px 0;font-size:11px}.dot{width:10px;height:10px;border-radius:2px;display:inline-block}.fullscreen{position:absolute;right:16px;top:16px;z-index:4}.uploadPreview{max-height:120px;width:100%;object-fit:cover;border-radius:10px;border:1px solid #24493d;display:none;margin-top:8px}.print-note{display:none}@media print{body{overflow:visible;background:#fff;color:#111}.top,.panel,.right,.hint,.fullscreen{display:none}.layout{position:static;display:block}.stage{height:auto;background:#fff}.canvas3d{display:none}.map2d{display:block!important;position:static;height:720px}.print-note{display:block;color:#111;padding:16px}.map2d canvas{height:720px}}
</style></head><body>
<div class="top"><span class="brand">GEA-H Smart City Studio</span><span class="badge">Lotissement IA + Ville 3D</span><a href="/">← Accueil</a><a href="/modules/studio3d.php">Studio intérieur</a><a href="/modules/maison3d.php">Maison 3D</a></div>
<div class="layout">
  <aside class="panel">
    <h2>Projet & terrain</h2>
    <div class="sec"><h3>Importer photo / plan</h3>
      <input type="file" id="planFile" accept="image/*,.pdf"><img id="preview" class="uploadPreview" alt="aperçu">
      <p class="small">Importez photo drone, capture, plan image ou PDF. L’IA prépare une base de découpage. Le géomètre complète ensuite les données techniques.</p>
    </div>
    <div class="sec"><h3>Données du terrain</h3>
      <label>Superficie totale</label><div class="row"><input id="area" type="number" value="10000" min="100" step="100" style="flex:2"><select id="unit" style="flex:1"><option value="m2">m²</option><option value="ha">ha</option></select></div>
      <label>Forme du terrain</label><select id="shape"><option value="rectangle">Rectangle</option><option value="irregular">Irrégulier / à ajuster</option><option value="long">Terrain long</option><option value="corner">Terrain d’angle</option></select>
      <label>Objectif</label><select id="goal"><option value="residential">Lotissement résidentiel</option><option value="mixed">Mixte : villas + commerces</option><option value="eco">Écoquartier</option><option value="premium">Résidence premium</option></select>
      <label>Surface moyenne par lot</label><input id="lotSize" type="number" value="400" min="100" step="50">
      <label>Largeur voirie principale</label><input id="roadWidth" type="number" value="12" min="6" step="1">
      <div class="row" style="margin-top:10px"><button class="btn gold" id="generate">✨ Générer lotissement IA</button><button class="btn" id="askMore">Infos géomètre</button></div>
    </div>
    <div class="sec"><h3>Maquettes prêtes</h3><div class="cards">
      <div class="card" data-tpl="res"><b>Cité résidentielle</b>Lots + parc + voiries</div>
      <div class="card" data-tpl="mix"><b>Quartier mixte</b>Commerces + logements</div>
      <div class="card" data-tpl="eco"><b>Écoquartier</b>Vert + chemins doux</div>
      <div class="card" data-tpl="lux"><b>Résidence premium</b>Grandes villas + sécurité</div>
    </div></div>
    <div class="sec"><h3>Ville 3D</h3><div class="row"><button class="btn" data-add="villa">Villa</button><button class="btn" data-add="duplex">Duplex</button><button class="btn" data-add="immeuble">Immeuble</button><button class="btn" data-add="tour">Tour</button></div><div class="row" style="margin-top:8px"><button class="btn blue" id="sync3d">Créer la maquette 3D</button><button class="btn dark" id="toggleView">Vue plan / 3D</button></div></div>
  </aside>
  <main class="stage" id="stage">
    <button class="btn fullscreen" id="fs">⛶ Plein écran</button>
    <canvas id="c3d" class="canvas3d"></canvas>
    <div id="map2d" class="map2d"><canvas id="planCanvas"></canvas></div>
    <div class="hint">Plan IA : lots, routes, bornes, espaces verts · Cliquez sur un lot pour le sélectionner · Export disponible après paiement/abonnement</div>
  </main>
  <aside class="panel right">
    <h2>Assistant IA urbaniste</h2>
    <div class="sec ai"><h3>Demande à l'IA</h3><textarea id="prompt">Propose un lotissement moderne avec des voiries, des bornes, des espaces verts et une zone commerciale légère.</textarea><button class="btn gold" id="aiBtn">🤖 Proposer un plan</button><div id="aiReply" class="aiReply" style="margin-top:8px">L’assistant attend les données du terrain.</div></div>
    <div class="sec"><h3>Résumé technique</h3><div class="stats"><div class="stat"><b id="stLots">0</b><span>Lots</span></div><div class="stat"><b id="stRoads">0 m</b><span>Voiries</span></div><div class="stat"><b id="stGreen">0%</b><span>Espaces verts</span></div><div class="stat"><b id="stCost">0</b><span>Estimation</span></div></div><p class="mini">Estimation indicative : à faire valider par géomètre, urbaniste, architecte et autorités compétentes.</p></div>
    <div class="sec"><h3>Légende</h3><div class="legend"><span><i class="dot" style="background:#d9b77a"></i>Lots</span><span><i class="dot" style="background:#50555a"></i>Voiries</span><span><i class="dot" style="background:#3e8f55"></i>Espaces verts</span><span><i class="dot" style="background:#ef4444"></i>Bornes</span><span><i class="dot" style="background:#60a5fa"></i>Équipements</span></div></div>
    <div class="sec paywall"><h3>Rentabilité du module</h3><p class="small"><b>Gratuit :</b> aperçu, brouillon IA, maquette simple.<br><b>Payant :</b> export PDF, image HD, vidéo, dossier technique.<br><b>Abonnement Pro :</b> projets illimités, bibliothèque complète, assistance IA avancée.</p><div class="row"><button class="btn gold" id="exportImg">📸 Image HD</button><button class="btn" id="printPlan">🖨 Plan PDF</button><button class="btn" id="recordVideo">🎥 Vidéo</button></div></div>
    <div class="sec"><h3>Projet</h3><div class="row"><button class="btn" id="save">💾 Sauver</button><button class="btn" id="load">📂 Charger</button><button class="btn red" id="reset">Vider</button></div></div>
  </aside>
</div>
<div class="print-note"><h1>GEA-H Smart City Studio — Plan de lotissement</h1><p>Document généré pour aperçu. Validation obligatoire par géomètre expert et autorités compétentes.</p></div>
<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/build/three.min.js"></script><script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
<script>
(function(){
var parcels=[],roads=[],greens=[],bornes=[],equip=[],bgImg=null,selected=-1,view='3d';
var pc=document.getElementById('planCanvas'),px=pc.getContext('2d'),map=document.getElementById('map2d'),stage=document.getElementById('stage');
var scene,camera,renderer,controls,items=[],ground;
function money(n){return Math.round(n).toLocaleString('fr-FR')+' FCFA'}
function areaM2(){var a=parseFloat(document.getElementById('area').value||0);return document.getElementById('unit').value==='ha'?a*10000:a}
function resize(){pc.width=map.clientWidth||stage.clientWidth;pc.height=map.clientHeight||stage.clientHeight;if(renderer){renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}draw2d()}
window.addEventListener('resize',resize);
function init3d(){scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc4e8);camera=new THREE.PerspectiveCamera(55,stage.clientWidth/stage.clientHeight,.1,1000);camera.position.set(36,32,44);renderer=new THREE.WebGLRenderer({canvas:document.getElementById('c3d'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight);renderer.shadowMap.enabled=true;controls=new THREE.OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x556677,.85));var sun=new THREE.DirectionalLight(0xfff2d6,1);sun.position.set(30,50,20);sun.castShadow=true;scene.add(sun);ground=new THREE.Mesh(new THREE.BoxGeometry(100,.2,70),new THREE.MeshStandardMaterial({color:0x4f8f3a,roughness:1}));ground.position.y=-.1;ground.receiveShadow=true;scene.add(ground);scene.add(new THREE.GridHelper(100,40,0x335544,0x244033));animate()}
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}
function rect(x,y,w,h,type){return {x:x,y:y,w:w,h:h,type:type||'lot'}}
function generate(tpl){var A=areaM2(),lot=parseFloat(document.getElementById('lotSize').value||400),goal=document.getElementById('goal').value;if(tpl==='lux'){lot=800;goal='premium'}if(tpl==='eco'){lot=350;goal='eco'}if(tpl==='mix'){goal='mixed'}
var reserve=goal==='eco'?0.25:(goal==='mixed'?0.18:0.12),road=0.18,usable=A*(1-reserve-road),n=Math.max(4,Math.floor(usable/lot));
parcels=[];roads=[];greens=[];bornes=[];equip=[];var W=100,H=70,margin=6;roads.push(rect(0,H/2-3,W,6,'road'));roads.push(rect(W/2-3,0,6,H,'road'));if(goal==='mixed')roads.push(rect(0,13,W,4,'road'));
var cols=Math.ceil(Math.sqrt(n*W/H)),rows=Math.ceil(n/cols),pw=(W-2*margin)/cols,ph=(H-2*margin)/rows,k=0;
for(var r=0;r<rows;r++){for(var c=0;c<cols;c++){if(k>=n)break;var x=margin+c*pw,y=margin+r*ph;if(Math.abs((x+pw/2)-W/2)<5||Math.abs((y+ph/2)-H/2)<5)continue;parcels.push(rect(x+1,y+1,pw-2,ph-2,'lot'));k++;}}
if(goal==='eco'){greens.push(rect(8,8,20,14,'green'));greens.push(rect(70,48,22,14,'green'));}else{greens.push(rect(6,52,22,12,'green'));}
if(goal==='mixed'){equip.push(rect(4,4,22,9,'commerce'));equip.push(rect(74,4,18,9,'school'));}else if(goal==='premium'){equip.push(rect(4,4,18,8,'gate'));}
parcels.forEach(function(p){bornes.push({x:p.x,y:p.y},{x:p.x+p.w,y:p.y},{x:p.x+p.w,y:p.y+p.h},{x:p.x,y:p.y+p.h});});
selected=-1;draw2d();sync3d();aiSummary();}
function draw2d(){px.clearRect(0,0,pc.width,pc.height);var sx=pc.width/100,sy=pc.height/70;if(bgImg){px.globalAlpha=.28;px.drawImage(bgImg,0,0,pc.width,pc.height);px.globalAlpha=1}else{var grd=px.createLinearGradient(0,0,pc.width,pc.height);grd.addColorStop(0,'#173b2c');grd.addColorStop(1,'#0e221c');px.fillStyle=grd;px.fillRect(0,0,pc.width,pc.height)}
roads.forEach(function(r){px.fillStyle='#50555a';px.fillRect(r.x*sx,r.y*sy,r.w*sx,r.h*sy);px.strokeStyle='#f7d56b';px.setLineDash([8,8]);px.beginPath();px.moveTo((r.x+r.w/2)*sx,r.y*sy);px.lineTo((r.x+r.w/2)*sx,(r.y+r.h)*sy);px.stroke();px.setLineDash([])});
greens.forEach(function(g){px.fillStyle='#3e8f55';px.fillRect(g.x*sx,g.y*sy,g.w*sx,g.h*sy);px.fillStyle='rgba(255,255,255,.8)';px.font='12px Arial';px.fillText('Espace vert',g.x*sx+6,g.y*sy+18)});
equip.forEach(function(e){px.fillStyle=e.type==='commerce'?'#60a5fa':'#8b5cf6';px.fillRect(e.x*sx,e.y*sy,e.w*sx,e.h*sy);px.fillStyle='#fff';px.font='12px Arial';px.fillText(e.type,e.x*sx+5,e.y*sy+18)});
parcels.forEach(function(p,i){px.fillStyle=i===selected?'#f7d56b':'#d9b77a';px.fillRect(p.x*sx,p.y*sy,p.w*sx,p.h*sy);px.strokeStyle='#3d2d18';px.strokeRect(p.x*sx,p.y*sy,p.w*sx,p.h*sy);px.fillStyle='#1d160b';px.font='11px Arial';px.fillText('Lot '+(i+1),p.x*sx+5,p.y*sy+16)});
px.fillStyle='#ef4444';bornes.forEach(function(b){px.beginPath();px.arc(b.x*sx,b.y*sy,3,0,Math.PI*2);px.fill()});}
pc.addEventListener('click',function(e){var r=pc.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*70;selected=parcels.findIndex(function(p){return x>=p.x&&x<=p.x+p.w&&y>=p.y&&y<=p.y+p.h});draw2d();});
function clear3d(){items.forEach(function(o){scene.remove(o)});items=[]}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.85})}
function building(w,d,h,c){var g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));body.position.y=h/2;body.castShadow=true;g.add(body);var roof=new THREE.Mesh(new THREE.BoxGeometry(w+.3,.3,d+.3),mat(0xb8bdc1));roof.position.y=h+.15;g.add(roof);for(var i=0;i<Math.max(2,Math.floor(w/2));i++){var win=new THREE.Mesh(new THREE.BoxGeometry(.45,.55,.05),mat(0xa8cdec));win.position.set(-w/2+1+i*1.5,h*.55,d/2+.03);g.add(win)}return g}
function sync3d(){if(!scene)return;clear3d();roads.forEach(function(r){var o=new THREE.Mesh(new THREE.BoxGeometry(r.w,.08,r.h),mat(0x40454a));o.position.set(r.x-50+r.w/2,.03,r.y-35+r.h/2);items.push(o);scene.add(o)});greens.forEach(function(g){var o=new THREE.Mesh(new THREE.BoxGeometry(g.w,.09,g.h),mat(0x3e8f55));o.position.set(g.x-50+g.w/2,.05,g.y-35+g.h/2);items.push(o);scene.add(o)});equip.forEach(function(e){var o=building(e.w*.5,e.h*.7,4,e.type==='commerce'?0x60a5fa:0x8b5cf6);o.position.set(e.x-50+e.w/2,0,e.y-35+e.h/2);items.push(o);scene.add(o)});parcels.forEach(function(p,i){var b=building(Math.min(4,p.w*.45),Math.min(4,p.h*.45),2.8+(i%3)*1.4,0xd9b77a);b.position.set(p.x-50+p.w/2,0,p.y-35+p.h/2);items.push(b);scene.add(b)});bornes.forEach(function(b){var o=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,1,10),mat(0xef4444));o.position.set(b.x-50,.5,b.y-35);items.push(o);scene.add(o)});updateStats()}
function updateStats(){var A=areaM2(),roadLen=roads.reduce(function(s,r){return s+(r.w>r.h?r.w:r.h)},0)*Math.sqrt(A/(100*70));var greenArea=greens.reduce(function(s,g){return s+g.w*g.h},0)/(100*70)*100;var cost=parcels.length*650000+roadLen*95000+greenArea*A*500;document.getElementById('stLots').textContent=parcels.length;document.getElementById('stRoads').textContent=Math.round(roadLen)+' m';document.getElementById('stGreen').textContent=Math.round(greenArea)+'%';document.getElementById('stCost').textContent=money(cost)}
function aiSummary(){var A=areaM2();var msg='Proposition IA :\n- Terrain analysé : '+Math.round(A).toLocaleString('fr-FR')+' m².\n- Découpage proposé : '+parcels.length+' lots, avec bornes à chaque angle de lot.\n- Voiries principales et secondaires prévues selon le gabarit indiqué.\n- Espaces verts et équipements positionnés selon le type de projet.\n\nInformations à demander au géomètre : coordonnées GPS, limites exactes, contraintes administratives, servitudes, topographie, accès existants, zone inondable, réseaux disponibles.\n\nImportant : le plan est une assistance de conception. Validation obligatoire par un géomètre expert et les autorités compétentes.';document.getElementById('aiReply').textContent=msg;updateStats()}
function askMore(){document.getElementById('aiReply').textContent='Pour produire un lotissement plus précis, l’IA a besoin de :\n1. Superficie exacte et coordonnées des limites.\n2. Plan cadastral/topographique si disponible.\n3. Largeur minimale imposée des voiries.\n4. Superficie minimale des lots.\n5. Emplacements des accès au terrain.\n6. Contraintes : réserves, servitudes, zones non constructibles.\n7. Orientation souhaitée des lots.\n8. Besoin en espaces verts, commerces, école, parking, sécurité.'}
function aiPrompt(){var p=document.getElementById('prompt').value.toLowerCase();if(p.includes('éco')||p.includes('vert'))document.getElementById('goal').value='eco';if(p.includes('commerce')||p.includes('mix'))document.getElementById('goal').value='mixed';if(p.includes('premium')||p.includes('luxe'))document.getElementById('goal').value='premium';generate();}
document.getElementById('generate').onclick=function(){generate()};document.getElementById('askMore').onclick=askMore;document.getElementById('aiBtn').onclick=aiPrompt;document.querySelectorAll('[data-tpl]').forEach(function(x){x.onclick=function(){generate(this.dataset.tpl)}});document.getElementById('sync3d').onclick=sync3d;document.getElementById('toggleView').onclick=function(){view=view==='3d'?'2d':'3d';map.classList.toggle('active',view==='2d');document.getElementById('c3d').classList.toggle('hidden',view==='2d');draw2d()};document.querySelectorAll('[data-add]').forEach(function(b){b.onclick=function(){parcels.push(rect(20+Math.random()*55,14+Math.random()*40,8,8,'lot'));draw2d();sync3d()}});
document.getElementById('planFile').onchange=function(ev){var f=ev.target.files[0];if(!f)return;var img=document.getElementById('preview');if(f.type.startsWith('image/')){var u=URL.createObjectURL(f);img.src=u;img.style.display='block';bgImg=new Image();bgImg.onload=draw2d;bgImg.src=u;document.getElementById('aiReply').textContent='Image importée. Lancez “Générer lotissement IA”. L’IA utilisera l’image comme fond de travail et proposera un découpage à ajuster.'}else{img.style.display='none';document.getElementById('aiReply').textContent='PDF importé. Pour cette version navigateur, convertissez le plan en image si vous voulez l’afficher en fond. Les données du terrain peuvent déjà être utilisées pour générer le lotissement.'}}
document.getElementById('exportImg').onclick=function(){draw2d();var a=document.createElement('a');a.download='gea-h-plan-lotissement.png';a.href=pc.toDataURL('image/png');a.click()};document.getElementById('printPlan').onclick=function(){view='2d';map.classList.add('active');document.getElementById('c3d').classList.add('hidden');draw2d();setTimeout(function(){window.print()},300)};document.getElementById('recordVideo').onclick=function(){alert('Option vidéo : lancez la vue 3D en plein écran puis utilisez l’export vidéo payant/pro. Cette version prépare le flux, l’intégration serveur sera branchée ensuite.')};document.getElementById('fs').onclick=function(){(stage.requestFullscreen||stage.webkitRequestFullscreen||stage.msRequestFullscreen).call(stage)};document.getElementById('save').onclick=function(){localStorage.setItem('geah_city_ai',JSON.stringify({parcels:parcels,roads:roads,greens:greens,bornes:bornes,equip:equip,area:document.getElementById('area').value,unit:document.getElementById('unit').value,goal:document.getElementById('goal').value,lotSize:document.getElementById('lotSize').value,roadWidth:document.getElementById('roadWidth').value}));alert('Projet enregistré sur cet appareil.')};document.getElementById('load').onclick=function(){var d=JSON.parse(localStorage.getItem('geah_city_ai')||'null');if(!d){alert('Aucun projet.');return}parcels=d.parcels||[];roads=d.roads||[];greens=d.greens||[];bornes=d.bornes||[];equip=d.equip||[];['area','unit','goal','lotSize','roadWidth'].forEach(function(k){if(d[k]&&document.getElementById(k))document.getElementById(k).value=d[k]});draw2d();sync3d();aiSummary()};document.getElementById('reset').onclick=function(){if(confirm('Vider le projet ?')){parcels=[];roads=[];greens=[];bornes=[];equip=[];draw2d();sync3d();updateStats()}};
init3d();resize();generate('res');
})();
</script></body></html>
