<?php
require_once __DIR__.'/../core.php';
if(is_admin()){ header('Location:/admin/index.php'); exit; }
if(($_GET['logout']??'')==='1'){ unset($_SESSION['user']); header('Location:/'); exit; }
if(!is_user()){ header('Location:/modules/connexion.php'); exit; }
$u=current_user(); $ph=trim($u['phone']??''); $em=strtolower(trim($u['email']??''));
$myRes=array_values(array_filter(read_json('reservations.json',[]),function($r) use($ph){ return $ph!=='' && trim($r['phone']??'')===$ph; }));
$myOrd=array_values(array_filter(read_json('orders.json',[]),function($o) use($ph){ return $ph!=='' && trim($o['buyer_phone']??'')===$ph; }));
function _ff($n){ return number_format((int)$n,0,',',' ').' FCFA'; }
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mon espace client — GEA-HOLDING</title><link rel="stylesheet" href="/assets/css/style.css?v=110"><style>.dash-hero{background:linear-gradient(135deg,#063d2e,#07111d);padding:42px 0;color:white}.dash-top{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}.dash-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:-28px}.dash-card{background:rgba(255,255,255,.98);color:#0f172a;border-radius:22px;padding:20px;border:1px solid #e5eee9;box-shadow:0 18px 50px rgba(0,0,0,.12)}.dash-card h3{margin:0;color:#063d2e}.dash-card p{color:#64748b}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.quick a{text-decoration:none}.pill{display:inline-block;background:#dcfce7;color:#166534;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:900}@media(max-width:850px){.dash-grid,.quick{grid-template-columns:1fr}}</style></head>
<body><header class="header"><div class="wrap nav"><a class="brand" href="/">GEA-HOLDING.SAU</a><nav class="menu"><a href="/">Accueil</a><a href="/modules/properties.php">Biens</a><a href="/modules/residences.php">Résidences</a><a href="/modules/hotels.php">Hôtels</a><a href="/modules/showroom-tv.php">Showroom TV</a><a href="/modules/logout.php">Déconnexion</a></nav></div></header>
<section class="dash-hero"><div class="wrap dash-top"><div><span class="pill">Mon espace personnel</span><h1 style="margin:12px 0 4px">Bonjour, <?=e($u['name']??'Client GEA-H')?></h1><p style="margin:0;color:#dbeafe">Gérez uniquement vos réservations, paiements, reçus, dossiers, annonces et projets 3D.</p><?php if(!empty($u['client_ref'])): ?><p style="margin:10px 0 0;padding:8px 12px;background:rgba(255,255,255,.12);border-radius:10px;display:inline-block">🪪 Votre référence client : <b style="color:#ffd98a"><?=e($u['client_ref'])?></b></p><?php endif; ?></div><img src="/assets/img/logo-geah.jpeg" style="width:86px;height:86px;border-radius:24px;background:white;padding:5px;object-fit:cover" alt="GEA-H"></div></section>

<section class="section" style="padding-top:18px">
  <div class="wrap">
    <div class="dash-card" style="margin-bottom:14px;background:linear-gradient(135deg,#063d2e,#07111d);color:white">
      <h3 style="color:#ffd98a;margin:0 0 6px">📺 Showroom GEA-H accessible même connecté</h3>
      <p style="margin:0;color:#dbeafe">Vous pouvez regarder les biens validés qui défilent et GEA-H TV sans vous déconnecter.</p>
    </div>
  </div>
</section>
<?php include __DIR__.'/../_home_biens_screen.php'; $GLOBALS['GEAH_HIDE_TV_PROPERTY_SCREEN']=true; include __DIR__.'/../_geah_tv.php'; ?>
<section class="section"><div class="wrap"><div class="dash-grid"><div class="dash-card"><h3><?=count($myRes)?></h3><p>Réservations</p></div><div class="dash-card"><h3><?=count($myOrd)?></h3><p>Commandes</p></div><div class="dash-card"><h3>0</h3><p>Favoris</p></div><div class="dash-card"><h3>IA</h3><p>Assistant disponible</p></div></div>
<div class="quick" style="margin-top:18px"><a class="dash-card" href="/modules/properties.php"><h3>🏠 Voir les biens</h3><p>Terrains, maisons, locations et ventes.</p></a><a class="dash-card" href="/modules/deposer.php"><h3>📢 Déposer une annonce</h3><p>Publier un bien après validation GEA-H.</p></a><a class="dash-card" href="/modules/mes-annonces.php"><h3>✏️ Mes annonces</h3><p>Modifier ou supprimer mes annonces.</p></a><a class="dash-card" href="/modules/maison3d.php"><h3>📐 Concevoir en 3D</h3><p>Modèles de maison, plan imprimable après paiement.</p></a><a class="dash-card" href="/modules/mes-dossiers.php"><h3>🗂️ Mes dossiers & reçus</h3><p>Documents, contrats, reçus et références.</p></a><a class="dash-card" href="/modules/payer-loyer.php"><h3>🔑 Payer mon loyer</h3><p>Réglez votre loyer en ligne avec votre référence de bail et obtenez votre reçu.</p></a><a class="dash-card" href="/ask.php"><h3>🤖 Assistant IA</h3><p>Demander de l'aide pour choisir ou aménager.</p></a></div>
  <div class="dash-card" style="margin-top:18px"><h3>👤 Profil</h3><p><a class="btn btn-light" href="/modules/change-password.php">Modifier mon mot de passe</a></p><p>📧 <?=e($u['email']??'')?><?php if($ph): ?> · 📞 <?=e($ph)?><?php endif; ?><?php if(!empty($u['account_type'])): ?> · Type : <?=e($u['account_type'])?><?php endif; ?></p><p style="margin-bottom:0">🔐 Vérification SMS/OTP prête à activer après configuration du fournisseur SMS.</p></div>
  <h2>🔑 Mes réservations</h2><?php if(!$myRes): ?><div class="dash-card"><p>Aucune réservation pour l'instant. <a href="/modules/residences.php" style="color:#0f7a5b;font-weight:900">Voir les résidences →</a></p></div><?php endif; ?><?php foreach(array_reverse($myRes) as $r): $paid=in_array($r['status']??'',['paid','Traité']); ?><div class="dash-card" style="border-left:5px solid <?=$paid?'#16a34a':'#d4a23a'?>"><b><?=($r['type']??'')==='hotel'?'🏨':(($r['type']??'')==='property'?'🏠':'🛏️')?> <?=e($r['item_title']??'')?></b> <span class="status <?=$paid?'ok':'warn'?>" style="font-size:12px"><?=$paid?'PAYÉ':'EN ATTENTE'?></span><p><?=e($r['date']??'')?><?php if(!empty($r['arrival'])): ?> · arrivée <?=e($r['arrival'])?><?php endif; ?><?php if(($r['amount']??0)>0): ?> · <?=_ff($r['amount'])?><?php endif; ?></p></div><?php endforeach; ?>
  <h2>🛒 Mes commandes</h2><?php if(!$myOrd): ?><div class="dash-card"><p>Aucune commande pour l'instant.</p></div><?php endif; ?><?php foreach(array_reverse($myOrd) as $o): $paid=($o['status']??'')==='paid'; ?><div class="dash-card" style="border-left:5px solid <?=$paid?'#16a34a':'#d4a23a'?>"><b>🛒 <?=e($o['item_title']??'')?></b> <span class="status <?=$paid?'ok':'warn'?>" style="font-size:12px"><?=$paid?'PAYÉE':'EN ATTENTE'?></span><p><?=e($o['date']??'')?> · Total <?=_ff($o['total']??0)?><?php if(!empty($o['delivered'])): ?> · 🚚 Livré<?php endif; ?></p></div><?php endforeach; ?>
</div></section><?php echo geah_footer(); ?></body></html>