<?php
require_once __DIR__.'/../core.php';
if(!is_user()){ header('Location:/modules/connexion.php?redirect='.rawurlencode('/modules/mes-dossiers.php')); exit; }
$u=current_user(); $email=strtolower(trim($u['email']??'')); $phone=preg_replace('/[^0-9+]/','',trim($u['phone']??''));
$docs=read_json('client_documents.json',[]);
$mine=array_values(array_filter($docs,function($d) use($email,$phone){
    $de=strtolower(trim($d['client_email']??'')); $dp=preg_replace('/[^0-9+]/','',trim($d['client_phone']??''));
    return ($email && $de===$email) || ($phone && $dp===$phone);
}));
function gd_groups(){ return ['client_locatif'=>'Client locatif','client_acheteur_bien'=>'Acheteur de bien','client_terrain'=>'Client terrain','client_residence'=>'Résidence / hôtel','client_construction'=>'Construction / 3D','prospect'=>'Prospect','partenaire'=>'Partenaire','autre'=>'Autre']; }
$groups=gd_groups();
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mes dossiers & reçus — GEA-H</title><link rel="stylesheet" href="/assets/css/style.css?v=110"><style>.hero-doc{background:linear-gradient(135deg,#063d2e,#07111d);color:white;padding:38px 0}.doc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.doc-card{background:white;border:1px solid #e5eee9;border-radius:20px;padding:18px;box-shadow:0 14px 40px rgba(0,0,0,.08)}.ref{font-family:monospace;font-weight:900;color:#0f7a5b}.pill{display:inline-block;border-radius:99px;padding:5px 9px;background:#ecfdf5;color:#166534;font-size:12px;font-weight:800}@media(max-width:850px){.doc-grid{grid-template-columns:1fr}}@media print{.header,.no-print,.geah-chat-btn,.geah-chat-panel{display:none!important}.doc-card{break-inside:avoid}}</style></head><body><header class="header"><div class="wrap nav"><a class="brand" href="/">GEA-HOLDING.SAU</a><nav class="menu"><a href="/modules/compte.php">Mon espace</a><a href="/modules/properties.php">Biens</a><a href="/modules/showroom-tv.php">GEA-H TV</a><a href="/modules/logout.php">Déconnexion</a></nav></div></header><section class="hero-doc"><div class="wrap"><h1>Mes dossiers, reçus & documents</h1><p>Retrouvez vos documents GEA-H avec leurs références, téléchargez-les ou imprimez-les.</p></div></section><section class="section"><div class="wrap"><div class="doc-card" style="margin-bottom:16px"><b>Client :</b> <?=e($u['name']??'')?> · <?=e($email)?> · <?=e($phone)?><br><b>Total documents :</b> <?=count($mine)?></div><?php if(!$mine): ?><div class="doc-card"><p>Aucun dossier numérique disponible pour le moment. Dès qu'un reçu, contrat, attestation ou dossier est enregistré par GEA-H, il apparaîtra ici.</p></div><?php endif; ?><div class="doc-grid"><?php foreach($mine as $d): ?><div class="doc-card"><span class="pill"><?=e($groups[$d['client_group']??'']??($d['client_group']??''))?></span><h3><?=e($d['title']??'Document')?></h3><p>Référence document<br><span class="ref"><?=e($d['reference']??'')?></span></p><p>Référence dossier<br><span class="ref"><?=e($d['dossier_reference']??'')?></span></p><p><b>Type :</b> <?=e($d['document_type']??'')?> <br><b>Montant :</b> <?=money($d['amount']??0)?><br><b>Statut :</b> <?=e($d['status']??'')?></p><?php if(!empty($d['note'])): ?><p><?=e($d['note'])?></p><?php endif; ?><p class="no-print"><a class="btn" href="/modules/client-document-download.php?id=<?=e($d['id'])?>">Télécharger</a> <button class="btn" onclick="window.print()">Imprimer</button></p></div><?php endforeach; ?></div></div></section><?php echo geah_footer(); ?></body></html>