<?php require_once __DIR__.'/../modules/geah-tv-engine.php';  require_once __DIR__.'/../core.php'; require_once __DIR__.'/auth.php'; require_role('dashboard'); ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tableau de bord général</title><link rel="stylesheet" href="/assets/css/style.css?v=110"><link rel="stylesheet" href="/assets/css/geah-v28-premium-dashboard.css?v=110"></head><body><div class="admin-layout"><?php include __DIR__.'/sidebar.php'; ?><main class="admin-main" style="display:block!important;min-height:0!important;height:auto!important;padding:20px 30px 40px!important;margin:0!important;overflow:visible!important;position:relative!important;"><?php $p=data_list('properties');$r=data_list('residences');$h=data_list('hotels');$a=data_list('auctions');$tv=data_list('geah_tv');$pr=data_list('prospects');$s=settings(); ?><?php $bgImgs=[]; foreach(($p??[]) as $bien){ $im=geah_property_images($bien); if(!empty($im)){ $bgImgs[]=media_src($im[0]); } if(count($bgImgs)>=8) break; } ?>
<?php if(count($bgImgs)<4){ foreach(array_merge($r??[],$h??[]) as $item){ $im=geah_property_images($item); if(!empty($im)){ $bgImgs[]=media_src($im[0]); } if(count($bgImgs)>=8) break; } } ?>
<?php if(empty($bgImgs)){ $bgImgs=['/assets/img/logo-geah.jpeg']; } ?>
<div class="dash-bien-strip"><div class="dash-bien-strip-track"><?php foreach(array_merge($bgImgs,$bgImgs) as $bi): ?><div class="dash-bien-thumb" style="background-image:url('<?=e($bi)?>')"></div><?php endforeach; ?></div></div>
<h1>Tableau de bord général</h1><div class="kpis"><div class="kpi"><span>Mode</span><b><?=e($s['site_mode'])?></b></div><div class="kpi"><span>Biens</span><b><?=count($p)?></b></div><div class="kpi"><span>Résidences</span><b><?=count($r)?></b></div><div class="kpi"><span>Hôtels</span><b><?=count($h)?></b></div><div class="kpi"><span>Enchères</span><b><?=count($a)?></b></div><div class="kpi"><span>GEA-H TV</span><b><?=count($tv)?></b></div><div class="kpi"><span>Prospects</span><b><?=count($pr)?></b></div></div><?php if(auth_role()==='super'): ?><div class="grid"><div class="card"><h3>Tests</h3><p><a class="btn btn-gold" href="/admin/assistant.php">Tester Assistant IA</a></p><p><a class="btn btn-light" href="/admin/api-manager.php">Tester API</a></p></div><div class="card"><h3>Création</h3><p><a class="btn btn-light" href="/admin/properties.php">Ajouter bien</a></p><p><a class="btn btn-light" href="/admin/residences.php">Ajouter résidence</a></p><p><a class="btn btn-light" href="/admin/geah-tv.php">Ajouter GEA-H TV</a></p></div></div><?php else: ?><div class="card" style="border-left:4px solid #d4a23a"><p>🔒 Les outils de test et de création rapide sont réservés au Super Administrateur. Utilisez le menu à gauche pour accéder aux sections qui vous ont été autorisées.</p></div><?php endif; ?>
<div class="card" style="margin-top:18px">
  <h3>🖥️ Écran public — biens + GEA-H TV</h3>
  <p>Visible même quand vous êtes connecté en admin : les biens validés défilent et GEA-H TV joue en continu.</p>
  <p><a class="btn btn-gold" href="/modules/showroom-tv.php" target="_blank">Ouvrir en plein écran</a> <a class="btn btn-light" href="/" target="_blank">Voir l'accueil connecté</a></p>
  <iframe src="/modules/showroom-tv.php" style="width:100%;height:520px;border:1px solid rgba(212,162,58,.35);border-radius:18px;background:#050b12" loading="lazy"></iframe>
</div></main></div><script>
(function(){const saved=localStorage.getItem('geah_theme')||'dark';if(saved==='light')document.body.classList.add('light-mode');function ready(){const btn=document.createElement('button');btn.className='theme-toggle';function label(){btn.textContent=document.body.classList.contains('light-mode')?'🌙 Mode sombre':'☀️ Mode clair'}btn.onclick=function(){document.body.classList.toggle('light-mode');localStorage.setItem('geah_theme',document.body.classList.contains('light-mode')?'light':'dark');label()};label();document.body.appendChild(btn)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();})();
</script><script src="/assets/js/geah-v30-tv-engine.js" defer></script></body></html>