<?php require_once __DIR__.'/../core.php'; require_once __DIR__.'/auth.php';
$c=payments_config(); $err=''; $ok='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $amount=(int)($_POST['amount']??100); $channel=$_POST['channel']??'ALL';
  if($amount<100) $err='Montant minimum : 100 FCFA.';
  else { $txid='TEST-GEAH-'.time().'-'.rand(100,999); $_SESSION['last_txid']=$txid;
    $res=cinetpay_init($txid,$amount,'Test paiement GEA-H '.$channel,$channel,'GEA-H Test');
    if(!empty($res['ok']) && !empty($res['url'])){ header('Location:'.$res['url']); exit; }
    else $err=$res['error']??'Erreur inconnue.';
  }
}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Test paiement</title><link rel="stylesheet" href="/assets/css/style.css?v=110"></head><body><div class="admin-layout"><?php include __DIR__.'/sidebar.php'; ?><main class="admin-main"><h1>Tester les paiements</h1><div class="card"><h2>État actuel</h2><p><b>CinetPay :</b> <?=($c['cinetpay_apikey']&&$c['cinetpay_site_id'])?'✅ configuré':'⚠️ non configuré'?></p><p><b>Mobile Money direct :</b> <?=($c['momo_orange']||$c['momo_mtn']||$c['momo_moov']||$c['momo_wave'])?'✅ disponible':'⚠️ aucun numéro'?></p><p style="color:var(--muted)">Le test ouvre CinetPay. En mode TEST, tu peux vérifier sans vraie collecte selon ton compte CinetPay. En production, ce sont de vrais paiements.</p></div><?php if($err): ?><p class="status warn">⚠️ <?=e($err)?></p><?php endif; ?><form class="card" method="post"><h2>Lancer un test CinetPay</h2><div class="form-grid"><label>Montant test<input type="number" min="100" step="5" name="amount" value="100"></label><label>Moyen<select name="channel"><option value="ALL">Carte + Mobile Money</option><option value="MOBILE_MONEY">Mobile Money uniquement</option><option value="CREDIT_CARD">Carte bancaire uniquement</option></select></label></div><button class="btn btn-primary">Tester maintenant</button></form><div class="card"><h2>Mobile Money direct</h2><ul><?php if($c['momo_orange']): ?><li>Orange Money : <b><?=e($c['momo_orange'])?></b></li><?php endif; ?><?php if($c['momo_mtn']): ?><li>MTN MoMo : <b><?=e($c['momo_mtn'])?></b></li><?php endif; ?><?php if($c['momo_moov']): ?><li>Moov Money : <b><?=e($c['momo_moov'])?></b></li><?php endif; ?><?php if($c['momo_wave']): ?><li>Wave : <b><?=e($c['momo_wave'])?></b></li><?php endif; ?></ul><?php if(!$c['momo_orange']&&!$c['momo_mtn']&&!$c['momo_moov']&&!$c['momo_wave']): ?><p class="status warn">Aucun numéro Mobile Money n’est renseigné. Va dans Admin > Paiements.</p><?php endif; ?></div></main></div></body></html>