<?php require_once __DIR__.'/../core.php'; require_admin();
$settings = read_json('performance_settings.json', ['default_mode'=>'auto','tv_quality'=>'auto','lazy_images'=>true,'cache_enabled'=>true]);
if($_SERVER['REQUEST_METHOD']==='POST'){
  $settings['default_mode']=$_POST['default_mode']??'auto';
  $settings['tv_quality']=$_POST['tv_quality']??'auto';
  $settings['lazy_images']=!empty($_POST['lazy_images']);
  $settings['cache_enabled']=!empty($_POST['cache_enabled']);
  write_json('performance_settings.json',$settings); log_action('Paramètres performance mis à jour');
  header('Location: performance.php?ok=1'); exit;
}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Performance & forfait internet</title><link rel="stylesheet" href="/assets/css/style.css?v=110"></head><body><?php echo admin_header('Performance & économie internet'); ?><main class="admin-main"><div class="card"><h2>Mode Internet Intelligent</h2><?php if(isset($_GET['ok'])): ?><p class="success">Paramètres enregistrés.</p><?php endif; ?><form method="post" class="form-grid"><label>Mode par défaut<select name="default_mode"><option value="auto" <?=($settings['default_mode']==='auto'?'selected':'')?>>Auto selon connexion</option><option value="eco" <?=($settings['default_mode']==='eco'?'selected':'')?>>Économie de données</option><option value="hd" <?=($settings['default_mode']==='hd'?'selected':'')?>>Qualité HD</option></select></label><label>Qualité GEA-H TV<select name="tv_quality"><option value="auto" <?=($settings['tv_quality']==='auto'?'selected':'')?>>Auto</option><option value="240p" <?=($settings['tv_quality']==='240p'?'selected':'')?>>Ultra économie 240p</option><option value="360p" <?=($settings['tv_quality']==='360p'?'selected':'')?>>Économie 360p</option><option value="480p" <?=($settings['tv_quality']==='480p'?'selected':'')?>>Standard 480p</option><option value="720p" <?=($settings['tv_quality']==='720p'?'selected':'')?>>HD 720p</option></select></label><label><input type="checkbox" name="lazy_images" value="1" <?=!empty($settings['lazy_images'])?'checked':''?>> Chargement progressif des images</label><label><input type="checkbox" name="cache_enabled" value="1" <?=!empty($settings['cache_enabled'])?'checked':''?>> Cache navigateur / Service Worker</label><button class="btn btn-gold">Enregistrer</button></form></div><div class="card"><h3>Conseil production</h3><p>Active Cloudflare devant le domaine, puis Brotli/Gzip et cache statique. Pour GEA-H TV, privilégie HLS multi-qualité quand les vidéos deviennent lourdes.</p></div></main></body></html>
