<?php require_once __DIR__.'/../core.php'; require_once __DIR__.'/auth.php'; require_role('voice_orders');
$me=auth_user(); $staff=geah_admin_users(); $orders=read_json('voice_orders.json',[]); $msg='';
function staff_label($u){return ($u['name']??$u['email']).' — '.(auth_roles_labels()[$u['role']??'agent']??($u['role']??''));}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $a=$_POST['action']??'';
  if($a==='create'){
    $to=strtolower(trim($_POST['to']??'')); $text=trim($_POST['text']??'');
    if($to===''||$text==='') $msg='⚠️ Destinataire et ordre obligatoires.';
    else { $orders[]=['id'=>time().rand(10,99),'from_email'=>$me['email']??'','from_name'=>$me['name']??'','to_email'=>$to,'text'=>$text,'priority'=>$_POST['priority']??'normale','status'=>'envoyé','history'=>[['at'=>now(),'by'=>$me['name']??'','text'=>'Ordre créé'.(($_POST['source']??'')==='voice'?' par commande vocale':'')]],'created_at'=>now()]; write_json('voice_orders.json',$orders); $msg='✅ Ordre envoyé et historisé.'; }
  }
  if($a==='status'){
    $id=(int)($_POST['id']??0); $st=$_POST['status']??'lu'; $note=trim($_POST['note']??'');
    foreach($orders as &$o){ if((int)($o['id']??0)===$id){ $o['status']=$st; $o['history'][]=['at'=>now(),'by'=>$me['name']??'','text'=>'Statut : '.$st.($note?' — '.$note:'')]; } } unset($o); write_json('voice_orders.json',$orders); $msg='✅ Statut mis à jour.';
  }
}
$mine=array_values(array_filter($orders,fn($o)=>strtolower($o['to_email']??'')===strtolower($me['email']??'')));
$sent=array_values(array_filter($orders,fn($o)=>strtolower($o['from_email']??'')===strtolower($me['email']??'') || auth_can('users')));
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ordres vocaux IA</title><link rel="stylesheet" href="/assets/css/style.css?v=110"><style>.order{border-left:4px solid #d4af37}.micbar{background:#07131d;border:1px solid var(--border);border-radius:14px;padding:12px;margin-top:8px}.order p{white-space:pre-wrap}</style></head><body><div class="admin-layout"><?php include __DIR__.'/sidebar.php'; ?><main class="admin-main"><h1>🎙️ Ordres vocaux & IA interne</h1><p class="status warn">Les ordres vocaux sont transcrits avec consentement de l'utilisateur qui clique sur le micro. Le système n'enregistre pas secrètement l'audio.</p><?php if($msg) echo '<p class="status ok">'.e($msg).'</p>'; ?>
<form class="card" method="post" id="orderForm"><input type="hidden" name="action" value="create"><input type="hidden" name="source" id="source" value="manual"><div class="form-grid"><label>Destinataire<select name="to" required><option value="">— Choisir —</option><?php foreach($staff as $u): ?><option value="<?=e($u['email']??'')?>"><?=e(staff_label($u))?></option><?php endforeach; ?></select></label><label>Priorité<select name="priority"><option>normale</option><option>haute</option><option>urgente</option></select></label></div><label>Ordre / instruction<textarea name="text" id="orderText" rows="4" required placeholder="Dictez ou écrivez l'instruction..."></textarea></label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px"><button type="button" class="btn btn-light" id="micBtn">🎙️ Dicter l'ordre</button><button type="button" class="btn" id="readBtn">🔊 Lire à voix haute</button><button class="btn btn-gold">Envoyer l'ordre</button></div><div class="micbar" id="micStatus">Micro prêt.</div></form>
<h2>📥 Ordres reçus</h2><?php if(!$mine): ?><div class="card">Aucun ordre reçu.</div><?php endif; foreach(array_reverse($mine) as $o): ?><div class="card order"><b><?=e(strtoupper($o['priority']??'normale'))?> · <?=e($o['status']??'')?></b><p><?=e($o['text']??'')?></p><small>De <?=e($o['from_name']??'')?> — <?=e($o['created_at']??'')?></small><form method="post" style="margin-top:8px;display:flex;gap:6px;flex-wrap:wrap"><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?=e($o['id'])?>"><select name="status"><option>lu</option><option>accepté</option><option>en cours</option><option>rendu</option><option>terminé</option><option>besoin de précision</option></select><input name="note" placeholder="Rapport / commentaire"><button class="btn btn-gold">Valider</button></form><details><summary>Historique</summary><?php foreach($o['history']??[] as $h): ?><div>• <?=e($h['at'])?> — <?=e($h['by'])?> : <?=e($h['text'])?></div><?php endforeach; ?></details></div><?php endforeach; ?>
<h2>📤 Ordres envoyés / supervision</h2><?php foreach(array_reverse(array_slice($sent,-30)) as $o): ?><div class="card"><b><?=e($o['to_email']??'')?> — <?=e($o['status']??'')?></b><p><?=e($o['text']??'')?></p><small><?=e($o['created_at']??'')?></small></div><?php endforeach; ?>
</main></div><script>function say(t){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';speechSynthesis.speak(u);}catch(e){}}readBtn.onclick=()=>say(orderText.value||'Aucun texte');let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){let rec=new SR();rec.lang='fr-FR';rec.continuous=false;rec.onstart=()=>micStatus.textContent='🎙️ Parlez maintenant...';rec.onresult=e=>{let txt=e.results[0][0].transcript;orderText.value=(orderText.value?orderText.value+'\n':'')+txt;source.value='voice';micStatus.textContent='✅ Transcription ajoutée : '+txt;say('Ordre dicté. Vous pouvez vérifier puis envoyer.');};rec.onerror=()=>micStatus.textContent='Micro non disponible.';micBtn.onclick=()=>rec.start();}else{micBtn.onclick=()=>alert('Commande vocale non supportée sur ce navigateur.');}</script></body></html>